GRANT ALL ON app.* to 'app'@'%' IDENTIFIED BY 'appPass';

USE app;

CREATE TABLE IF NOT EXISTS `votes` (
id INT UNSIGNED AUTO_INCREMENT,
vote TINYINT UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET utf8;
